# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tr8n}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Berkovich"]
  s.date = %q{2010-05-05}
  s.description = %q{Crowd-sourced translation and localization for Rails}
  s.email = %q{michael@geni.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".project",
     "README",
     "Rakefile",
     "VERSION"
  ]
  s.homepage = %q{http://github.com/berk/tr8n}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Crowd-sourced translation for Rails.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

