#!/usr/bin/env ruby

if ARGV.include?('-d')
  ARGV.delete('-d')
  ARGV.unshift('start') unless ARGV.detect{|a| ['start', 'restart'].include?(a)}

  root = File.expand_path(File.dirname(__FILE__) + '/..')
  ARGV << "--rails=#{root}"

  system("ruby #{root}/vendor/gems/sweatshop/lib/sweatshop/sweatd.rb #{ARGV.join(' ')}")
  exit $?.exitstatus
else
  puts "Loading Rails..."
  require File.dirname(__FILE__) + '/../config/environment'
  puts "Listening for new tasks..."
  Sweatshop.do_all_tasks
end
